// shell/src/app/publisher/publisher.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-publisher',
  templateUrl: './publisher.component.html',
  styleUrl: './publisher.component.scss',
})
export class PublisherComponent {
  handleEmitEvent = () => {
    window.dispatchEvent(
      new CustomEvent('info', {
        detail: { data: { name: 'Hi' } },
      })
    );
  };
}

<button style="margin-top: 15px" (click)="handleEmitEvent()">
  Emit Events from Angular
</button>

// react-mfe/src/pages/Publisher.tsx
import React from "react";

function Publisher() {
  const EmitEvent = () => {
    window.dispatchEvent(
      new CustomEvent("info", {
        detail: { data: { name: "Vishal" } },
      })
    );
  };
  return (
    <div>
      <div>
        <button onClick={() => EmitEvent()}>Emit Events from React</button>
      </div>
    </div>
  );
}

export default Publisher;
