// shell/src/app/receiver/receiver.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-receiver',
  templateUrl: './receiver.component.html',
  styleUrl: './receiver.component.scss',
})
export class ReceiverComponent {
  eventData: any;
  ngOnInit(): void {
    // window.addEventListener('info', (evt) => {
    //   // const data = evt.detail.data;
    //   console.log('angular', evt);
    // });

    window.addEventListener('info', (evt: Event) => {
      const customEvent = evt as CustomEvent;
      if (customEvent) {
        const eventData = customEvent.detail;
        console.log('Angular Shell', eventData.data.name);
        this.eventData = eventData.data.name; // Assign to a component property for rendering
      }
    });
  }
}

<div>
  <h2>Event Subscribe in Angular</h2>
  <div>Event data: {{ eventData }}</div>
</div>

// react-mfe/src/pages/Receiver.tsx
import React, { useState, useEffect } from "react";

function Receive() {
  const [eventData, setEventData] = useState<string>("");

  useEffect(() => {
    const subscribeEvent = (e: Event) => {
      const customEvent = e as CustomEvent;
      if (customEvent && customEvent.detail && customEvent.detail.data) {
        console.log("React App", customEvent.detail.data.name);
        customEvent.preventDefault(); // Prevent the mini-infobar from appearing on mobile
        setEventData(customEvent.detail.data.name);
      }
    };

    window.addEventListener("info", subscribeEvent);

    return () => {
      window.removeEventListener("info", subscribeEvent);
    };
  }, []);

  return (
    <div>
      {/* Render eventData in your UI */}
      <h2>Event Subscribe in React</h2>
      <p>Event data: {eventData}</p>
    </div>
  );
}

export default Receive;
